name: aaroh_chat_example
description: Example app for the aaroh_chat SDK.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  aaroh_chat:
    path: ../

flutter:
  uses-material-design: true
